server:
  port: 0

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: aggregator-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ru.practicum.kafka.deserializer.UserActionAvroDeserializer
      topic:
        user-actions: stats.user-actions.v1
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.practicum.kafka.serializer.GeneralAvroSerializer
      topic:
        events-similarity: stats.events-similarity.v1

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  output:
    ansi:
      enabled: always

aggregator:
  weights:
    VIEW: 0.4
    REGISTER: 0.8
    LIKE: 1.0

logging:
  level:
    org.springframework.cloud.loadbalancer: WARN
    com.netflix.discovery: WARN
    aggregator: DEBUG